<?php

namespace App\Services;

use App\Models\Helmet;
use App\Models\Rider;
use App\Models\SelfiePrompt;
use App\Models\SelfieSubmission;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SelfieService
{
    /**
     * Save a selfie prompt generated by the mobile app.
     */
    public function createPrompt(Rider $rider): SelfiePrompt
    {
        return SelfiePrompt::create([
            'rider_id'       => $rider->id,
            'user_id'        => $rider->user_id,
            'prompt_sent_at' => now(),
            'status'         => 'pending',
        ]);
    }

    /**
     * Mark a prompt as accepted by the rider (rider tapped "Scan QR").
     */
    public function acceptPrompt(SelfiePrompt $prompt): SelfiePrompt
    {
        if (!$prompt->isPending()) {
            throw new \RuntimeException('This prompt has already been responded to or has expired.');
        }

        $prompt->update([
            'status'       => 'accepted',
            'responded_at' => now(),
        ]);

        return $prompt->fresh();
    }


    /**
     * Mark a prompt as accepted by the rider (rider tapped "Scan QR").
     */
    public function rejectPrompt(SelfiePrompt $prompt): SelfiePrompt
    {
        if (!$prompt->isPending()) {
            throw new \RuntimeException('This prompt has already been responded to or has expired.');
        }

        $prompt->update([
            'status'       => 'rejected',
            'responded_at' => now(),
        ]);

        return $prompt->fresh();
    }

    /**
     * Submit a QR code scan + GPS coordinates for an accepted prompt.
     * Validates that the scanned QR code belongs to the rider's assigned helmet.
     */
    public function submitSelfie(SelfiePrompt $prompt, Rider $rider, array $data): SelfieSubmission
    {
        return DB::transaction(function () use ($prompt, $rider, $data) {
            // Resolve the helmet from the scanned QR code
            $helmet = Helmet::where('qr_code', $data['qr_code'])->firstOrFail();

            // Verify the scanned helmet is the one assigned to this rider
            $isAssigned = $rider->currentAssignment()
                ->where('helmet_id', $helmet->id)
                ->exists();

            if (!$isAssigned) {
                throw new \RuntimeException('The scanned QR code does not match your assigned helmet.');
            }

            $submission = SelfieSubmission::create([
                'selfie_prompt_id' => $prompt->id,
                'rider_id'         => $rider->id,
                'user_id'          => $rider->user_id,
                'helmet_id'        => $helmet->id,
                'qr_code'          => $data['qr_code'],
                'latitude'         => $data['latitude'],
                'longitude'        => $data['longitude'],
                'submitted_at'     => now(),
                'status'           => 'pending_review',
            ]);

            // Mark prompt as completed
            $prompt->update(['status' => 'accepted']);

            Log::info('QR submission received', [
                'rider_id'      => $rider->id,
                'prompt_id'     => $prompt->id,
                'submission_id' => $submission->id,
                'helmet_id'     => $helmet->id,
                'qr_code'       => $data['qr_code'],
            ]);

            return $submission->load(['selfiePrompt', 'helmet']);
        });
    }

    /**
     * Get the current pending/accepted prompt for the logged-in rider.
     */
    public function getActivePromptForRider(Rider $rider): ?SelfiePrompt
    {
        return SelfiePrompt::where('rider_id', $rider->id)
            ->whereIn('status', ['pending', 'accepted'])
            ->latest('prompt_sent_at')
            ->first();
    }

    /**
     * Paginated list of prompts for a rider (admin or rider view).
     */
    public function getPromptsForRider(Rider $rider, array $filters = []): LengthAwarePaginator
    {
        $query = SelfiePrompt::where('rider_id', $rider->id)
            ->with('submission')
            ->latest('prompt_sent_at');

        if (!empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        return $query->paginate($filters['per_page'] ?? 15);
    }

    /**
     * Format a prompt for API response.
     */
    public function formatPrompt(SelfiePrompt $prompt): array
    {
        return [
            'id'             => $prompt->id,
            'status'         => $prompt->status,
            'prompt_sent_at' => $prompt->prompt_sent_at?->toIso8601String(),
            'responded_at'   => $prompt->responded_at?->toIso8601String(),
            'has_submission' => $prompt->submission !== null,
        ];
    }

    /**
     * Format a submission for API response.
     */
    public function formatSubmission(SelfieSubmission $submission): array
    {
        return [
            'id'               => $submission->id,
            'selfie_prompt_id' => $submission->selfie_prompt_id,
            'qr_code'          => $submission->qr_code,
            'latitude'         => $submission->latitude,
            'longitude'        => $submission->longitude,
            'submitted_at'     => $submission->submitted_at?->toIso8601String(),
            'status'           => $submission->status,
            'helmet' => $submission->helmet ? [
                'id'          => $submission->helmet->id,
                'helmet_code' => $submission->helmet->helmet_code,
            ] : null,
        ];
    }
}